
spring:
  application:
    name: UserMicroservicesConfigServer
  cloud:
   config:
    server:
     git:
      uri: https://github.com/Tribhuwan2917/Hotal_Microservioces_Configuration
      clone-on-update: true
      bootstrap: true

server:
  port: 8085
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:900/eureka
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: 'true'
info:
  application:
    name: ConfigServerOfUserMicroServices
    instanceNumber: '1'
    version: v1.0.1
    description: This Server Belong To ConfigServerOfUserMicroServices, which Basically provide Remote Configuration.