
server:
  port: 8082
spring:
  application:
    name: HotalServices
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/userservicesdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: configserver:http://localhost:8085
  profiles:
    active: default
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:900/eureka/
#  instance:
#    prefer-ip-address: true
HotalServices:
  CreateHotal: createHotal
  DeleteHotal: deleteHotal/{hotalId}
  Get_All_Hotals: getAllHotals
  Get_By_Id:
    URL: getHotal/{hotalId}
  UpdateHotal: updateHotal
  base:
    URL: /user-services/v1/Hotals/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: 'true'
info:
  application:
    name: HotalService
    instanceNumber: '1'
    version: v1.0.1
    description: This Server Belong To HotalService, Which Provide Hotal Information To Users.